### ISSUE TITLE
SPM Installation Issue when using Packages

### ISSUE THREAD

**Issue by will-lumley** [ShenghaiWang/SwiftLlama#11]
Hi there. I tried installing SwiftLlama via SPM in my production app, but it failed. I tried in a test project as well, but I got the same error. The error is as follows:

```
Failed to resolve dependencies Dependencies could not be resolved because 'my_app_name' depends on 'swiftllama' 0.2.0..<1.0.0.
 'swiftllama' >= 0.2.0 cannot be used because package 'swiftllama' is required using a stable-version but 'swiftllama' depends on an unstable-version package 'llama.cpp' and no versions of 'swiftllama' match the requirement 0.2.1..<1.0.0.
```

For reference, this is my `Package.swift` and the platform is native macOS.

```swift
...
    dependencies: [
        .package(url: "https://github.com/ShenghaiWang/SwiftLlama.git", from: "0.2.0"),
    ],
    .target(
        name: "my_app_name",
        dependencies: [
            "SwiftLlama",
        ],
    )
...
```

Of note, this issue doesn't seem to appear when the package is integrated via Xcodes menu, but when using a modularised application and integrating SwiftLlama via it's `Package.swift` file it breaks.

**Comment by ShenghaiWang** [comment]
https://github.com/ShenghaiWang/SwiftLlama/pull/12
